version: "2.1"
services:
  chatroom-ms:
    container_name: chatroom-ms
    build: ./
    restart: on-failure
    ports:
      - "7000:8080"
    depends_on:
      - mongo-db
    environment:
      - MONGO_URL=mongo-db
      - MONGO_PORT=27017


  mongo-db:
    image: mongo:4
    container_name: mongo-db
    ports:
      - "7001:27017"
