version: "2.1"
services:
  chatroom-ms:
    container_name: chatroom-ms
    build: ./
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mongo-db


  mongo-db:
    image: mongo:4
    container_name: mongo-db
    ports:
      - "27017:27017"